### ISSUE TITLE
Emulate what OpenMPI does for getting the node / processors

### ISSUE THREAD

**Issue by qiqi** [qiqi/fds#5]
Cloned https://github.com/open-mpi/ompi.git

It looks like OpenMPI may also be looking for the PBS_NODEFILE environment variable when user calls mpiexec in a pbs/torque environment:

```
qiqi@ubuntu:~/git/ompi$ git grep PBS_NODEFILE
orte/mca/ras/tm/help-ras-tm.txt:No nodes were found in the PBS_NODEFILE:
orte/mca/ras/tm/ras_tm_component.c:    pbs_nodefile_env = getenv("PBS_NODEFILE");
```

Looking into the source, OpenMPI looks for pbs_nodefile under /var/torque/aux if the environment variable is not found. We have no machine to test this on. So just take note for now.

When in slurm, it may be also looking for SLURM_NODELIST environment variable:

```
qiqi@ubuntu:~/git/ompi$ git grep SLURM_NODELIST
orte/mca/ras/slurm/help-ras-slurm.txt:    SLURM_NODELIST
orte/mca/ras/slurm/help-ras-slurm.txt:    SLURM_NODELIST       value: %s
orte/mca/ras/slurm/ras_slurm_module.c:    slurm_node_str = getenv("SLURM_NODELIST");
orte/mca/ras/slurm/ras_slurm_module.c:                       "SLURM_NODELIST");
orte/mca/ras/slurm/ras_slurm_module.c: * @param *regexp A node regular expression from SLURM (i.e. SLURM_NODELIST)
orte/mca/ras/slurm/ras_slurm_module.c:                           1, regexp, tasks_per_node, "SLURM_NODELIST");
orte/mca/ras/slurm/ras_slurm_module.c:                               1, regexp, tasks_per_node, "SLURM_NODELIST");
orte/mca/ras/slurm/ras_slurm_module.c:                               1, regexp, tasks_per_node, "SLURM_NODELIST");
orte/mca/ras/slurm/ras_slurm_module.c:         * I would get SLURM_NODELIST=odin001 SLURM_TASKS_PER_NODE=4(x30)
orte/mca/schizo/slurm/schizo_slurm.c:    if (NULL == getenv("SLURM_NODELIST")) {
```

To run fds on Mira, we need to figure out what we need to do in a cobalt environment. What environment variable / file contains information about nodes / processors available for the current job?

**Comment by chaitan3** [comment]
In slurm, instead of mpirun if srun is used it will automatically choose the right number of nodes/processors from the available list. In an allocation we can use multiple sruns.

I'm sure torque also has the same functionality. I don't think there is any need to replicate openmpi functionality.
